name: Run JMeter Test and Export Output

on:
  push:
    paths:
      - '**.jmx'
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run JMeter Test
      uses: rbhadti94/apache-jmeter-action@v0.7.0
      with:
        testFilePath: FetchNames.jmx
        outputReportsFolder: reports/

    - name: Archive JMeter result.jtl
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-jtl-results
        path: reports/result.jtl

    - name: Archive output.csv
      uses: actions/upload-artifact@v4
      with:
        name: movie-output
        path: output.csv
